[build]
  functions = "netlify/functions"
  publish = "."

[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/app.html"
  status = 200
